add_newline = true
#format = """
#$directory\
#$git_branch\
#$git_status\
#$character\
#$cmd_duration"""

format = """
$username\
$hostname\
$sudo\
$directory\
$git_branch\
$git_status
$character
"""

right_format = """$cmd_duration"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[cmd_duration]
format = '[$duration]($style)'
min_time = 1_000

[directory]
format = "[$path]($style)(bold blue)[$read_only](bold #EE4B2B)($read_only_style) "
truncation_length = 4
truncation_symbol = './'
read_only = "  "

[git_branch]
style = "bold #7C83FD"

[git_metrics]
disabled = false

[git_status]
ahead = " ⇡ ${count}"
diverged = "⇕ ⇡ ${ahead_count} ⇣ ${behind_count}"
behind = "⇣ ${count}"
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#ff00dd"

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)@[$hostname](bold bright-red)\] '
trim_at = '.companyname.com'
disabled = false

[sudo]
disabled = false
format = '[$symbol]($style) '
style = 'bold #00AAFF'
symbol = ' '

[username]
style_user = 'blue bold'
style_root = 'red bold'
format = '\[[$user]($style)'
disabled = false
show_always = true
