# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

#  fileSystems."/" =
#    { device = "/dev/disk/by-uuid/c7aed3ee-80f7-4338-bc1d-e8201ca76a8d";
#      fsType = "btrfs";
#      options = [ "subvol=@" ];
#    };
#
#  fileSystems."/home" =
#    { device = "/dev/disk/by-uuid/c7aed3ee-80f7-4338-bc1d-e8201ca76a8d";
#      fsType = "btrfs";
#      options = [ "subvol=@home" ];
#    };
#
#  fileSystems."/nix" =
#    { device = "/dev/disk/by-uuid/c7aed3ee-80f7-4338-bc1d-e8201ca76a8d";
#      fsType = "btrfs";
#      options = [ "subvol=@nix" ];
#    };
#
#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/D714-790B";
#      fsType = "vfat";
#      options = [ "fmask=0022" "dmask=0022" ];
#    };
#
#  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
