#!/usr/bin/env bash

##Bash script to get basic system information (i know eww have some these but im doing it anyway)

help () {
  echo "
  Usage: sys_info [--active | --nowplaying]

    --active                          prints active window, truncates to 42
    --nowplaying-info                 prints artist and title using playerctl, i spent more time here than i'd like
    --nowplaying-time                 prints elapsed time 0 - 100 for progress bar usage
    --nowplaying-album                overcomplicated mess that fetches mpris:artUrl, if not available defaults to doki doki waku waku because why not
    --date                            prettier date
    --volume                          prints volume in 0-100, send hlep
    --microphone                      prints microphone volume in 0-100, why

    Added because I was lazy, but it works:

    volup                             increases volume by 5%
    voldown                           decreases volume by 5%
    micup                             increases mic volume by 5%
    micdown                           decreases mic volume by 5%

    "
}

get_active () {
  hyprctl activewindow -j | rg "title" | sed -e 's/"title": //g' -e 's/\(.\{42\}\).*/\1 /' | sed -e 's/"//' -e "s/..$//" | tr -d '\n'
}
get_volume () {
  local volume=$(wpctl get-volume @DEFAULT_SINK@ | sed 's/[^0-9]//g')
  local muted=$(wpctl get-mute @DEFAULT_SINK@)

  if [[ "$muted" == "yes" ]];then
    echo "Muted"
  else
    echo "${volume#0}"
  fi
}

get_microphone () {
  local volume=$(wpctl get-volume @DEFAULT_SOURCE@ | sed 's/[^0-9]//g')
  local muted=$(wpctl get-mute @DEFAULT_SOURCE@)

  if [[ "$muted" == "yes" ]];then
    echo "Muted"
  else
    echo "${volume#0}"
  fi
}

get_date () {
  date '+%H:%M %b %d, %Y'
}

vol_up () {
  eval "wpctl set-volume @DEFAULT_SINK@ 5%+"
}

vol_down () {
  eval "wpctl set-volume @DEFAULT_SINK@ 5%-"
}

mic_up () {
  eval "wpctl set-volume @DEFAULT_SOURCE@ 5%+"
}

mic_down () {
  eval "wpctl set-volume @DEFAULT_SOURCE@ 5%-"
}

##If works, it works oke
currentPlayer=$(playerctl metadata --format {{playerName}})

now_playing_artist () {
  local artist=$(playerctl metadata --format "{{ trunc(artist,16) }}")

  echo -e "$artist"
}

now_playing_title () {
  local title=$(playerctl metadata --format "{{ trunc(title,21) }}")

  echo -e "$title"
}

now_playing_time () {
  local position=$(playerctl metadata --format {{position}})
  local duration=$(playerctl metadata --format {{mpris:length}})

  local percentage=$((position * 100 / duration))

  echo "$percentage"
}

fetchFirefoxAlbum () {
  local firefoxPath=$(find ~/.mozilla/firefox/firefox-mpris/*)
  echo $firefoxPath
}

fetchAlbum () {
  local currentAlbum=$(playerctl metadata --format {{album}})
  local currentAlbumUrl=$(playerctl metadata --format {{mpris:artUrl}})
  local albumPath="/tmp/tmp.playerctl-is-a-dummy/$currentAlbum"
  if [[ -f $albumPath ]]; then
     echo $albumPath
  else
    mkdir -p /tmp/tmp.playerctl-is-a-dummy && find /tmp/tmp.playerctl-is-a-dummy -mindepth 1 -delete
    curl -o "$albumPath" "$currentAlbumUrl"
    echo $albumPath
  fi
}

fetchPlaceholder() {
  local placeholder="/tmp/tmp.playerctl-is-a-dummy/placeholder.png"
  local dokidokiwakuwaku="https://img.youtube.com/vi/RtTYQuO1j6w/mqdefault.jpg" ## Doki Doki Waku Waku Thumbnail at 320x120

  if [[ -f $placeholder ]]; then
    echo $placeholder
  else
    curl -o "$placeholder" "$dokidokiwakuwaku"
    echo "$placeholder"
  fi
}

now_playing_album () {
  if [[ $currentPlayer == firefox ]]; then
    fetchFirefoxAlbum
  elif [[ $currentPlayer == brave ]]; then
    fetchPlaceholder
  else
    fetchAlbum
  fi
}

now_playing_status () {
  local status=$(playerctl metadata --format {{status}})

  if [[ $status == "Playing" ]];then
     echo -e "\uead1"
  elif [[ $status == "Paused" ]];then
     echo -e "\uf04b"
  else
    echo -e "\uead1"
  fi
}

network_status () {
  local connected=false
  local default=$(ip route show default)
  local interface=$(echo "$default" | grep -oP 'dev \K\S+')

  while true; do
    # Ping a known server to check network connectivity
    ping -c 1 gnu.org >/dev/null 2>&1

    # Check the exit status of the ping command
    if [ $? -eq 0 ]; then
      if [ "$connected" = false ]; then
        echo -e "󰖟$interface"
        local connected=true
      fi
    else
      if [ "$connected" = true ]; then
        echo "󰪎$interface"
        local connected=false
      fi
    fi

    # Sleep for a specific interval before checking again
    sleep 5
  done
}

if [[ $# -eq 0 ]]; then
  help
fi

while true
do
  case "$1"
    in
    --active ) get_active; shift ;;
    --nowplaying-artist) now_playing_artist; shift ;;
    --nowplaying-title) now_playing_title; shift ;;
    --nowplaying-time) now_playing_time; shift ;;
    --nowplaying-album) now_playing_album; shift ;;
    --playerstatus) now_playing_status; shift ;;
    --date) get_date; shift;;
    --volume) get_volume; shift ;;
    --microphone) get_microphone; shift ;;
    volup) vol_up; shift;;
    voldown) vol_down; shift;;
    micup) mic_up; shift;;
    micdown) mic_down; shift;;
    -h | --help) help; shift ;;
    *)  break ;;
  esac
done
