# Workspaces

workspace = www,1

windowrule = float, file_progress
windowrule = float, confirm
windowrule = float, dialog
windowrule = float, download
windowrule = float, notification
windowrule = float, error
windowrule = float, splash
windowrule = float, confirmreset
windowrule = float, title:Open File
windowrule = float, title:branchdialog
windowrule = float, title:Salvar Arquivo
windowrule = float, Lxappearance
windowrule = float, Rofi
windowrule = animation none,Rofi
windowrule = float, viewnior
windowrule = float, Viewnior
windowrule = float, geeqie
windowrule = float, lxqt-archiver
windowrule = float, orage
windowrule = center, lxqt-archiver
windowrule = float, title:DevTools
windowrule = fullscreen, wlogout
windowrule = float, title:wlogout
windowrule = fullscreen, title:wlogout
windowrule = idleinhibit focus, mpv
windowrule = idleinhibit fullscreen, chromium
windowrule = float, title:^(Media viewer)$
windowrule = float, title:^(Volume Control)$
windowrule = float, title:^(Picture-in-Picture)$
windowrule = size 800 600, title:^(Volume Control)$
windowrule = move 75 44%, title:^(Volume Control)$
windowrule = opacity 0.92, pcmanfm-qt 
windowrule = float,^(pcmanfm-qt)$
windowrule = center,^(pcmanfm-qt)$
windowrulev2 = tile, ^:(pcmanfm-qt)$, title:^(Área de trabalho)$

# fix xwayland apps
windowrulev2 = rounding 0, xwayland:1, floating:1
windowrulev2 = center, class:^(.*jetbrains.*)$, title:^(Confirm Exit|Open Project|win424|win201|splash)$
windowrulev2 = size 640 400, class:^(.*jetbrains.*)$, title:^(splash)$
layerrule = blur, ^(gtk-layer-shell|wofi|anyrun)$
layerrule = ignorezero, ^(gtk-layer-shell|wofi|anyrun)$

# Remove blur from eww bar
layerrule =

# League of legends
windowrule = nomaxsize, riotclientux.exe
windowrule = size 1280 720,^(riotclientux.exe)$
windowrulev2 = float,workspace 5 silent,class:^(leagueclientux.exe)$,title:^(League of Legends)$
windowrule = size 1280 720,^(leagueclientux.exe)$
windowrule = center,^(leagueclientux.exe)$
windowrulev2 = fullscreen, workspace 5 silent,class:^(league of legends.exe)$,title:^(League of Legends (TM) Client)$ windowrule = size 1920 1080,^(league of legends.exe)$
windowrule = center,^(league of legends.exe)$
windowrule = forceinput,^(league of legends.exe)$

# Wine weird windows

windowrule = nomaxsize, explorer.exe
windowrule = nomaxsize, winecfg.exe
windowrule = nomaxsize, steam_proton
windowrule = size 415 470, winecfg.exe
windowrule = center, winecfg.exe
windowrule = float, zenity
windowrule = center, zenity
windowrule = center,steam_proton
windowrule = size 415 470, steam_proton

# Steam
windowrule = float, title:^(Steam - News)$ windowrule = size 700 830, title:^(Steam - News)$
windowrule = center, title:^(Steam - News)$
windowrule = float, title:^(Lista de amigos)$
windowrule = center, title:^(Lista de amigos)$
windowrule = size 335 800, title:^(Lista de amigos)$ 

windowrule = center, title:^(Warframe)$
# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Spawn in workspace x

windowrulev2 = workspace 3 silent, class:^(discord-screenaudio)$
windowrulev2 = workspace 6 silent, class:^(virt-manager)$
windowrulev2 = workspace 5 silent, class:^(steam*)$
windowrulev2 = workspace 5 silent, class:^(lutris*)$

windowrulev2 = workspace 5, class:^(Grapejuice)$

windowrulev2 = tile, title:^(Spotify)$
windowrulev2 = workspace 4 silent, title:^(Spotify)$
